all:smartptr auto_ptr unique_ptr shared_ptr 

smartptr:smartptr.cc
	g++ $^ -o $@

auto_ptr:auto_ptr.cc 
	g++ $^ -o $@

unique_ptr:unique_ptr.cc 
	g++ $^ -o $@

shared_ptr:shared_ptr.cc 
	g++ $^ -o $@
