.PHONY:all 

all:auto_ptr unique_ptr share_ptr 

auto_ptr:auto_ptr.cc
	g++ auto_ptr.cc -o auto_ptr 

unique_ptr:unique_ptr.cc 
	g++ unique_ptr.cc -o unique_ptr

share_ptr:share_ptr.cc 
	g++ share_ptr.cc -o share_ptr 
