.PHONY:all

all:count  insert  select  fast merge.cc  
	
count:count.cc 
	g++ count.cc -o count

insert:insert.cc 
	g++ insert.cc -o insert

select:SelectSort.cc 
	g++ SelectSort.cc -o select

fast:fast.cc 
	g++ fast.cc -o fast

merge: merge.cc 
	g++ merge.cc -o merge
